language: php
php:
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - 8.2
  - 8.3
  - nightly
matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
cache:
  directories:
    - $HOME/.composer/cache/files
before_script:
  - phpenv global "$TRAVIS_PHP_VERSION"
  - composer config extra.platform.php $TRAVIS_PHP_VERSION
install:
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  - travis_wait 30 composer install $flags
script:
  - ./vendor/bin/phpunit -c phpunit.xml
